export const artifactNames = [
    'honor',
    'kin',
    'distortion',
    'spite',
    'glass',
    'enigma',
    'sacrifice',
    'command',
    'spirit',
    'origin',
    'prestige',
    'dissonance',
    'tempus',
    'cognation',
];