export const commonItems = [
    {
        name: "Meat Nugget",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Meatnugget.webp",
    },
    {
        name: "Fire Shield",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Fireshield.webp",
    },
    {
        name: "Bustling Fungus",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Bustlingfungus.webp",
    },
    {
        name: "Lens Maker's Glasses",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Lensmakersglasses.webp",
    },
    {
        name: "Sprouting Egg",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Sproutingegg.webp",
    },
    {
        name: "Headstompers",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Headstompers.webp",
    },
    {
        name: "Life Savings",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Lifesavings.webp",
    },
    {
        name: "Barbed Wire",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Barbedwire.webp",
    },
    {
        name: "Rusty Knife",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Rustyknife.webp",
    },
    {
        name: "Mysterious Vial",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Mysteriousvial.webp",
    },
    {
        name: "Mortar Tube",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Mortartube.webp",
    },
    {
        name: "Warbanner",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Warbanner.webp",
    },
    {
        name: "Monster Tooth",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Monstertooth.webp",
    },
    {
        name: "Soldier's Syringe",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Soldierssyringe.webp",
    },
    {
        name: "Crowbar",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Crowbar.webp",
    },
    {
        name: "Medkit",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Medkit.webp",
    },
    {
        name: "Bundle of Fireworks",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Bundleoffireworks.webp",
    },
    {
        name: "Backup Magazine",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Backupmagazine.webp",
    },
    {
        name: "Topaz Brooch",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Topazbrooch.webp",
    },
    {
        name: "Taser",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Taser.webp",
    },
    {
        name: "Paul's Goat Hoof",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Paulsgoathoof.webp",
    },
    {
        name: "Bitter Root",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Bitterroot.webp",
    },
    {
        name: "Sticky Bomb",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Stickybomb.webp",
    },
    {
        name: "Snake Eyes",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Snakeeyes.webp",
    },
    {
        name: "Hermit's Scarf",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Hermitsscarf.webp",
    },
    {
        name: "Gasoline",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Gasoline.webp",
    },
    {
        name: "Spikestrip",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Spikestrip.webp",
    },
    {
        name: "Mocha",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Mocha.webp",
    },
    {
        name: "The Toxin",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Thetoxin.webp",
    },
    {
        name: "Mu Construct",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Muconstruct.webp",
    },
    {
        name: "Razor Penny",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Razorpenny.webp",
    },
    {
        name: "Arcane Blades",
        healing: false,
        utility: false,
        damage: false,
        image: "common/Arcaneblades.webp",
    },
];
