export const equipItems = [
    {
        name: "Safeguard Lantern",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Safeguardlantern.webp",
    },
    {
        name: "Snowglobe",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Snowglobe.webp",
    },
    {
        name: "Explorer's Key",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Explorerskey.webp",
    },
    {
        name: "Foreign Fruit",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Foreignfruit.webp",
    },
    {
        name: "Instant Minefield",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Instantminefield.webp",
    },
    {
        name: "Jar of Souls",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Jarofsouls.webp",
    },
    {
        name: "Carrara Marble",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Carraramarble.webp",
    },
    {
        name: "Sawmerang",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Sawmerang.webp",
    },
    {
        name: "Shattered Mirror",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Shatteredmirror.webp",
    },
    {
        name: "Disposable Missile Launcher",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Disposablemissilelauncher.webp",
    },
    {
        name: "Gold-Plated Bomb",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Goldplatedbomb.webp",
    },
    {
        name: "Drone Repair Kit",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Dronerepairkit.webp",
    },
    {
        name: "Thqwib",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Thqwib.webp",
    },
    {
        name: "Dynamite Plunger",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Dynamiteplunger.webp",
    },
    {
        name: "Mace Replica",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Macereplica.webp",
    },
    {
        name: "Gigantic Amethyst",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Giganticamethyst.webp",
    },
    {
        name: "Crudely-Drawn Buddy",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Crudelydrawnbuddy.webp",
    },
    {
        name: "Prescriptions",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Prescriptions.webp",
    },
    {
        name: "Shield Generator",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Shieldgenerator.webp",
    },
    {
        name: "Unstable Watch",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Unstable_Watch.webp",
    },
    {
        name: "Lost Doll",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Lostdoll.webp",
    },
    {
        name: "Pillaged Gold",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Pillagedgold.webp",
    },
    {
        name: "Captain's Brooch",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Captainsbrooch.webp",
    },
    {
        name: "The Back-Up",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Thebackup.webp",
    },
    {
        name: "Super Massive Leech",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Supermassiveleech.webp",
    },
    {
        name: "Glowing Meteorite",
        healing: false,
        utility: false,
        damage: false,
        image: "equipment/Glowingmeteorite.webp",
    },
];