export const rareItems = [
    {
        name: "Thallium",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Thallium.webp",
    },
    {
        name: "Tesla Coil",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Teslacoil.webp",
    },
    {
        name: "Old Box",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Oldbox.png",
    },
    {
        name: "Beating Embryo",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Beatingembryo.webp",
    },
    {
        name: "Permafrost",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Permafrost.png",
    },
    {
        name: "AtG Missile Mk. 2",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Atgmissilemk2.webp",
    },
    {
        name: "Happiest Mask",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Happiestmask.webp",
    },
    {
        name: "Plasma Chain",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Plasmachain.webp",
    },
    {
        name: "Heaven Cracker",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Heavencracker.webp",
    },
    {
        name: "Rapid Mitosis",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Rapidmitosis.webp",
    },
    {
        name: "Ceremonial Dagger",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Ceremonialdagger.webp",
    },
    {
        name: "Repulsion Armor",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Repulsionarmor.webp",
    },
    {
        name: "Brilliant Behemoth",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Brilliantbehemoth.webp",
    },
    {
        name: "Hardlight Afterburner",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Hardlightafterburner.webp",
    },
    {
        name: "Interstellar Desk Plant",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Interstellardeskplant.webp",
    },
    {
        name: "Laser Turbine",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Laserturbine.webp",
    },
    {
        name: "Wicked Ring",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Wickedring.webp",
    },
    {
        name: "Alien Head",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Alienhead.webp",
    },
    {
        name: "The Ol' Lopper",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Ollopper.webp",
    },
    {
        name: "The Hit List",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Thehitlist.webp",
    },
    {
        name: "Photon Jetpack",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Photonjetpack.webp",
    },
    {
        name: "Shattering Justice",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Shatteringjustice.webp",
    },
    {
        name: "Telescopic Sight",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Telescopicsight.webp",
    },
    {
        name: "Hyper-Threader",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Hyperthreader.webp",
    },
    {
        name: "Dio's Best Friend",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Diosbestfriend.webp",
    },
    {
        name: "Ancient Scepter",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Ancientscepter.webp",
    },
    {
        name: "Bottled Chaos",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Bottledchaos.webp",
    },
    {
        name: "Aegis",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Aegis.webp",
    },
    {
        name: "Substandard Duplicator",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Substandardduplicator.webp",
    },
    {
        name: "Classified Access Codes",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Classifiedaccesscodes.webp",
    },
    {
        name: "Umbrella",
        healing: false,
        utility: false,
        damage: false,
        image: "rare/Umbrella.webp",
    },
];