export const uncommonItems = [
    {
        name: "Time Keeper's Secret",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Timekeeperssecret.webp",
    },
    {
        name: "Smart Shopper",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Smartshopper.webp",
    },
    {
        name: "Infusion",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Infusion.webp",
    },
    {
        name: "Will-O'-The-Wisp",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Willothewisp.webp",
    },
    {
        name: "AtG Missile Mk. 1",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Atgmissilemk1.webp",
    },
    {
        name: "Tough Times",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Toughtimes.webp",
    },
    {
        name: "Energy Cell",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Energycell.webp",
    },
    {
        name: "Rusty Jetpack",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Rustyjetpack.png",
    },
    {
        name: "Leeching Seed",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Leechingseed.webp",
    },
    {
        name: "Ukulele",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Ukulele.webp",
    },
    {
        name: "Boxing Gloves",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Boxinggloves.webp",
    },
    {
        name: "Prison Shackles",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Prisonshackles.webp",
    },
    {
        healing: false,
        utility: false,
        damage: false,
        name: "Guardian's Heart",
        image: "uncommon/Guardiansheart.webp",
    },
    {
        name: "Hopoo Feather",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Hopoofeather.webp",
    },
    {
        name: "Frost Relic",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Frostrelic.webp",
    },
    {
        name: "Red Whip",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Redwhip.png",
    },
    {
        name: "Chargefield Generator",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Chargefieldgenerator.webp",
    },
    {
        name: "Arms Race",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Armsrace.webp",
    },
    {
        name: "Golden Gun",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Goldengun.webp",
    },
    {
        name: "56 Leaf Clover",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/56leafclover.webp",
    },
    {
        name: "Concussion Grenade",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Concussiongrenade.webp",
    },
    {
        name: "Dead Man's Foot",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Deadmansfoot.webp",
    },
    {
        name: "Toxic Centipede",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Toxiccentipede.webp",
    },
    {
        name: "Harvester's Scythe",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Harvestersscythe.webp",
    },
    {
        healing: false,
        utility: false,
        damage: false,
        name: "Panic Mines",
        image: "uncommon/Panicmines.webp",
    },
    {
        healing: false,
        utility: false,
        damage: false,
        name: "Predatory Instincts",
        image: "uncommon/Predatoryinstincts.webp",
    },
    {
        healing: false,
        utility: false,
        damage: false,
        name: "Royal Medallion",
        image: "uncommon/Royalmedallion.webp",
    },
    {
        name: "Prophet's Cape",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Prophetscape.webp",
    },
    {
        name: "Locked Jewel",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Lockedjewel.webp",
    },
    {
        name: "Hunter's Harpoon",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Huntersharpoon.webp",
    },
    {
        name: "Insecticide",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Insecticide.webp",
    },
    {
        name: "Decaying Sample",
        healing: false,
        utility: false,
        damage: false,
        image: "uncommon/Decayingsample.webp",
    },
];